version: "3.9"

services:
    db:
        image: postgres:14
        restart: always
        env_file:
          - ./.env
        ports:
            - 5433:5432
    back:
      build: ./back
      container_name: back
      env_file:
      - ./back/.env
      ports:
        - '3000:3000'
      depends_on:
        - db
      volumes:
        - ./back:/usr/src/back
        - /usr/src/back/node_modules
    front:
      build: ./front
      container_name: front
      ports:
        - '5173:5173'
      volumes:
        - ./front:/usr/src/front
        - /usr/src/front/node_modules